# Generated by Django 2.1.7 on 2019-05-21 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20190520_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 8, 58, 25, 878799, tzinfo=utc)),
        ),
    ]
