# Generated by Django 2.1.7 on 2019-05-21 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_auto_20190521_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 12, 35, 13, 756781, tzinfo=utc)),
        ),
    ]
